http://ocelma.net/MusicRecommendationDataset/lastfm-360K.html

## Import Libraries, Loading Dataset

In [1]:
import pandas as pd
import os

fname = '/Users/kenny_jung/aiffel/data/recommendata_iu/usersha1-artmbid-artname-plays.tsv'
col_names = ['user_id', 'artist_MBID', 'artist', 'play']   # 임의로 지정한 컬럼명
data = pd.read_csv(fname, sep='\t', names= col_names)      # sep='\t'로 주어야 tsv를 열 수 있습니다.  
data.head(10)

user_id  \
0  00000c289a1829a808ac09c00daf10bc3c4e223b   
1  00000c289a1829a808ac09c00daf10bc3c4e223b   
2  00000c289a1829a808ac09c00daf10bc3c4e223b   
3  00000c289a1829a808ac09c00daf10bc3c4e223b   
4  00000c289a1829a808ac09c00daf10bc3c4e223b   
5  00000c289a1829a808ac09c00daf10bc3c4e223b   
6  00000c289a1829a808ac09c00daf10bc3c4e223b   
7  00000c289a1829a808ac09c00daf10bc3c4e223b   
8  00000c289a1829a808ac09c00daf10bc3c4e223b   
9  00000c289a1829a808ac09c00daf10bc3c4e223b   

                            artist_MBID                   artist  play  
0  3bd73256-3905-4f3a-97e2-8b341527f805          betty blowtorch  2137  
1  f2fb0ff0-5679-42ec-a55c-15109ce6e320                die Ärzte  1099  
2  b3ae82c2-e60b-4551-a76d-6620f1b456aa        melissa etheridge   897  
3  3d6bbeb7-f90e-4d10-b440-e153c0d10b53                elvenking   717  
4  bbd2ffd7-17f4-4506-8572-c1ea58c3f9a8     juliette & the licks   706  
5  8bfac288-ccc5-448d-9573-c33ea2aa5c30    red hot chili peppers   691  
6  6531c8b1-76ea-4141-b270-eb1ac5b41375                   magica   545  
7  21f3573f-10cf-44b3-aeaa-26cccd8448b5  the black dahlia murder   507  
8  c5db90c4-580d-4f33-b364-fbaa5a3a58b5              the murmurs   424  
9  0639533a-0402-40ba-b6e0-18b067198b73               lunachicks   403

## Preprocessing

In [2]:
# 사용하는 컬럼만 남겨줍니다.
using_cols = ['user_id', 'artist', 'play']
data = data[using_cols]
data.head(10)

user_id                   artist  play
0  00000c289a1829a808ac09c00daf10bc3c4e223b          betty blowtorch  2137
1  00000c289a1829a808ac09c00daf10bc3c4e223b                die Ärzte  1099
2  00000c289a1829a808ac09c00daf10bc3c4e223b        melissa etheridge   897
3  00000c289a1829a808ac09c00daf10bc3c4e223b                elvenking   717
4  00000c289a1829a808ac09c00daf10bc3c4e223b     juliette & the licks   706
5  00000c289a1829a808ac09c00daf10bc3c4e223b    red hot chili peppers   691
6  00000c289a1829a808ac09c00daf10bc3c4e223b                   magica   545
7  00000c289a1829a808ac09c00daf10bc3c4e223b  the black dahlia murder   507
8  00000c289a1829a808ac09c00daf10bc3c4e223b              the murmurs   424
9  00000c289a1829a808ac09c00daf10bc3c4e223b               lunachicks   403

In [3]:
data['artist'] = data['artist'].str.lower() # 검색을 쉽게 하기 위해 아티스트 문자열을 소문자로 바꿔줍시다.
data.head(10)

user_id                   artist  play
0  00000c289a1829a808ac09c00daf10bc3c4e223b          betty blowtorch  2137
1  00000c289a1829a808ac09c00daf10bc3c4e223b                die ärzte  1099
2  00000c289a1829a808ac09c00daf10bc3c4e223b        melissa etheridge   897
3  00000c289a1829a808ac09c00daf10bc3c4e223b                elvenking   717
4  00000c289a1829a808ac09c00daf10bc3c4e223b     juliette & the licks   706
5  00000c289a1829a808ac09c00daf10bc3c4e223b    red hot chili peppers   691
6  00000c289a1829a808ac09c00daf10bc3c4e223b                   magica   545
7  00000c289a1829a808ac09c00daf10bc3c4e223b  the black dahlia murder   507
8  00000c289a1829a808ac09c00daf10bc3c4e223b              the murmurs   424
9  00000c289a1829a808ac09c00daf10bc3c4e223b               lunachicks   403

In [4]:
condition = (data['user_id']== data.loc[0, 'user_id'])
data.loc[condition]

user_id                   artist  play
0   00000c289a1829a808ac09c00daf10bc3c4e223b          betty blowtorch  2137
1   00000c289a1829a808ac09c00daf10bc3c4e223b                die ärzte  1099
2   00000c289a1829a808ac09c00daf10bc3c4e223b        melissa etheridge   897
3   00000c289a1829a808ac09c00daf10bc3c4e223b                elvenking   717
4   00000c289a1829a808ac09c00daf10bc3c4e223b     juliette & the licks   706
5   00000c289a1829a808ac09c00daf10bc3c4e223b    red hot chili peppers   691
6   00000c289a1829a808ac09c00daf10bc3c4e223b                   magica   545
7   00000c289a1829a808ac09c00daf10bc3c4e223b  the black dahlia murder   507
8   00000c289a1829a808ac09c00daf10bc3c4e223b              the murmurs   424
9   00000c289a1829a808ac09c00daf10bc3c4e223b               lunachicks   403
10  00000c289a1829a808ac09c00daf10bc3c4e223b         walls of jericho   393
11  00000c289a1829a808ac09c00daf10bc3c4e223b           letzte instanz   387
12  00000c289a1829a808ac09c00daf10bc3c4e223b                goldfrapp   361
13  00000c289a1829a808ac09c00daf10bc3c4e223b               horrorpops   358
14  00000c289a1829a808ac09c00daf10bc3c4e223b             the butchies   329
15  00000c289a1829a808ac09c00daf10bc3c4e223b            jack off jill   316
16  00000c289a1829a808ac09c00daf10bc3c4e223b         babes in toyland   310
17  00000c289a1829a808ac09c00daf10bc3c4e223b         dropkick murphys   302
18  00000c289a1829a808ac09c00daf10bc3c4e223b            all:my:faults   288
19  00000c289a1829a808ac09c00daf10bc3c4e223b                 le tigre   281
20  00000c289a1829a808ac09c00daf10bc3c4e223b               schandmaul   244
21  00000c289a1829a808ac09c00daf10bc3c4e223b                    edguy   232
22  00000c289a1829a808ac09c00daf10bc3c4e223b      maximum the hormone   231
23  00000c289a1829a808ac09c00daf10bc3c4e223b                 all ends   229
24  00000c289a1829a808ac09c00daf10bc3c4e223b             jack johnson   227
25  00000c289a1829a808ac09c00daf10bc3c4e223b                eluveitie   222
26  00000c289a1829a808ac09c00daf10bc3c4e223b                rasputina   220
27  00000c289a1829a808ac09c00daf10bc3c4e223b    london after midnight   210
28  00000c289a1829a808ac09c00daf10bc3c4e223b              the killers   208
29  00000c289a1829a808ac09c00daf10bc3c4e223b                  mutyumu   205
30  00000c289a1829a808ac09c00daf10bc3c4e223b             judas priest   198
31  00000c289a1829a808ac09c00daf10bc3c4e223b               rob zombie   198
32  00000c289a1829a808ac09c00daf10bc3c4e223b             the bosshoss   189
33  00000c289a1829a808ac09c00daf10bc3c4e223b         blue öyster cult   185
34  00000c289a1829a808ac09c00daf10bc3c4e223b             sandra nasic   183
35  00000c289a1829a808ac09c00daf10bc3c4e223b               john mayer   182
36  00000c289a1829a808ac09c00daf10bc3c4e223b           sleater-kinney   175
37  00000c289a1829a808ac09c00daf10bc3c4e223b                  the who   168
38  00000c289a1829a808ac09c00daf10bc3c4e223b                 disciple   154
39  00000c289a1829a808ac09c00daf10bc3c4e223b                  tanzwut   153
40  00000c289a1829a808ac09c00daf10bc3c4e223b               guano apes   151
41  00000c289a1829a808ac09c00daf10bc3c4e223b       the rolling stones   150
42  00000c289a1829a808ac09c00daf10bc3c4e223b          little big town   145
43  00000c289a1829a808ac09c00daf10bc3c4e223b              team dresch   137
44  00000c289a1829a808ac09c00daf10bc3c4e223b                    betty   135
45  00000c289a1829a808ac09c00daf10bc3c4e223b                       l7   135
46  00000c289a1829a808ac09c00daf10bc3c4e223b                bif naked   134
47  00000c289a1829a808ac09c00daf10bc3c4e223b               girlschool   134
48  00000c289a1829a808ac09c00daf10bc3c4e223b          the wallflowers   131

## EDA Dataset

In [5]:
# 유저 수
data['user_id'].nunique()

358868

In [6]:
# 아티스트 수
data['artist'].nunique()

291346

In [7]:
# 인기 많은 아티스트
artist_count = data.groupby('artist')['user_id'].count()
artist_count.sort_values(ascending=False).head(30)

artist
radiohead                77254
the beatles              76245
coldplay                 66658
red hot chili peppers    48924
muse                     46954
metallica                45233
pink floyd               44443
the killers              41229
linkin park              39773
nirvana                  39479
system of a down         37267
queen                    34174
u2                       33206
daft punk                33001
the cure                 32624
led zeppelin             32295
placebo                  32072
depeche mode             31916
david bowie              31862
bob dylan                31799
death cab for cutie      31482
arctic monkeys           30348
foo fighters             30144
air                      29795
the rolling stones       29754
nine inch nails          28946
sigur rós                28901
green day                28732
massive attack           28691
moby                     28232
Name: user_id, dtype: int64

In [8]:
# 유저별 몇 명의 아티스트를 듣고 있는지에 대한 통계
user_count = data.groupby('user_id')['artist'].count()
user_count.describe()

count    358868.000000
mean         48.863234
std           8.524272
min           1.000000
25%          46.000000
50%          49.000000
75%          51.000000
max         166.000000
Name: artist, dtype: float64

In [9]:
# 유저별 play횟수 중앙값에 대한 통계
user_median = data.groupby('user_id')['play'].median()
user_median.describe()

count    358868.000000
mean        142.187676
std         213.089902
min           1.000000
25%          32.000000
50%          83.000000
75%         180.000000
max       50142.000000
Name: play, dtype: float64

## Creating New User and Favorite

In [10]:
# 본인이 좋아하시는 아티스트 데이터로 바꿔서 추가하셔도 됩니다! 단, 이름은 꼭 데이터셋에 있는 것과 동일하게 맞춰주세요. 
my_favorite = ['black eyed peas' , 'maroon5' ,'jason mraz' ,'coldplay' ,'qeen']

# 'zimin'이라는 user_id가 위 아티스트의 노래를 30회씩 들었다고 가정하겠습니다.
my_playlist = pd.DataFrame({'user_id': ['kenny']*5, 'artist': my_favorite, 'play':[30]*5})

if not data.isin({'user_id':['kenny']})['user_id'].any():  # user_id에 'zimin'이라는 데이터가 없다면
    data = pd.concat([data, my_playlist])                            # 위에 임의로 만든 my_playlist 데이터를 추가해 줍니다. 

data.tail(10)       # 잘 추가되었는지 확인해 봅시다.

user_id           artist  play
17535650  sep 20, 2008       turbostaat    12
17535651  sep 20, 2008    cuba missouri    11
17535652  sep 20, 2008  little man tate    11
17535653  sep 20, 2008        sigur rós    10
17535654  sep 20, 2008       the smiths    10
0                kenny  black eyed peas    30
1                kenny          maroon5    30
2                kenny       jason mraz    30
3                kenny         coldplay    30
4                kenny             qeen    30

## Creating Index

In [11]:
# 고유한 유저, 아티스트를 찾아내는 코드
user_unique = data['user_id'].unique()
artist_unique = data['artist'].unique()

# 유저, 아티스트 indexing 하는 코드 idx는 index의 약자입니다.
user_to_idx = {v:k for k,v in enumerate(user_unique)}
artist_to_idx = {v:k for k,v in enumerate(artist_unique)}

In [12]:
# 인덱싱이 잘 되었는지 확인해 봅니다. 
print(user_to_idx['kenny'])    # 358869명의 유저 중 마지막으로 추가된 유저이니 358868이 나와야 합니다. 
print(artist_to_idx['qeen'])

358868
291347


## Indexing

In [13]:
# indexing을 통해 데이터 컬럼 내 값을 바꾸는 코드
# dictionary 자료형의 get 함수는 https://wikidocs.net/16 을 참고하세요.

# user_to_idx.get을 통해 user_id 컬럼의 모든 값을 인덱싱한 Series를 구해 봅시다. 
# 혹시 정상적으로 인덱싱되지 않은 row가 있다면 인덱스가 NaN이 될 테니 dropna()로 제거합니다. 
temp_user_data = data['user_id'].map(user_to_idx.get).dropna()
if len(temp_user_data) == len(data):   # 모든 row가 정상적으로 인덱싱되었다면
    print('user_id column indexing OK!!')
    data['user_id'] = temp_user_data   # data['user_id']을 인덱싱된 Series로 교체해 줍니다. 
else:
    print('user_id column indexing Fail!!')

# artist_to_idx을 통해 artist 컬럼도 동일한 방식으로 인덱싱해 줍니다. 
temp_artist_data = data['artist'].map(artist_to_idx.get).dropna()
if len(temp_artist_data) == len(data):
    print('artist column indexing OK!!')
    data['artist'] = temp_artist_data
else:
    print('artist column indexing Fail!!')

data

user_id column indexing OK!!
artist column indexing OK!!


user_id  artist  play
0         0       0  2137
1         0       1  1099
2         0       2   897
3         0       3   717
4         0       4   706
..      ...     ...   ...
0    358868     376    30
1    358868  270115    30
2    358868    3746    30
3    358868      62    30
4    358868  291347    30

[17535660 rows x 3 columns]

In [14]:
print(data)

    user_id  artist  play
0         0       0  2137
1         0       1  1099
2         0       2   897
3         0       3   717
4         0       4   706
..      ...     ...   ...
0    358868     376    30
1    358868  270115    30
2    358868    3746    30
3    358868      62    30
4    358868  291347    30

[17535660 rows x 3 columns]


In [15]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>


## One-time Play

In [16]:
# 1회만 play한 데이터의 비율을 보는 코드
only_one = data[data['play']==1]
one, all_data = len(only_one), len(data)
print(f'{one},{all_data}')
print(f'Ratio of only_one over all data is {one/all_data:.2%}')  # f-format에 대한 설명은 https://bit.ly/2DTLqYU

147739,17535660
Ratio of only_one over all data is 0.84%


## CSR Matrix

<!-- data = np.array([1,3,5,6,2,11,7,9,10,12])
indices = np.array([1,2,3,0,1,3,1,2,2,3])
indptr = np.array([0,3,6,8,10]) -->

In [17]:
# import numpy as np
# from scipy.sparse import csr_matrix

# # 제공된 데이터
# data = np.array([1,3,5,6,2,11,7,9,10,12])
# indices = np.array([1,2,3,0,1,3,1,2,2,3])
# indptr = np.array([0,3,6,8,10])

# # CSR Matrix 생성
# csr_mat = csr_matrix((data, indices, indptr), shape=(4,4))

# # CSR Matrix를 Dense Matrix 형태로 변환
# dense_mat = csr_mat.toarray()
# dense_mat

In [18]:
# 실습 위에 설명보고 이해해서 만들어보기
from scipy.sparse import csr_matrix

num_user = data['user_id'].nunique()
num_artist = data['artist'].nunique()

csr_data = csr_matrix((data.play, (data.user_id, data.artist)), shape= (num_user, num_artist))
csr_data

<358869x291348 sparse matrix of type '<class 'numpy.int64'>'
	with 17535578 stored elements in Compressed Sparse Row format>

## MF Model Training

In [19]:
from implicit.als import AlternatingLeastSquares
import os
import numpy as np

# implicit 라이브러리에서 권장하고 있는 부분입니다. 학습 내용과는 무관합니다.
os.environ['OPENBLAS_NUM_THREADS']='1'
os.environ['KMP_DUPLICATE_LIB_OK']='True'
os.environ['MKL_NUM_THREADS']='1'

In [20]:
# Implicit AlternatingLeastSquares 모델의 선언
als_model = AlternatingLeastSquares(factors=100, 
                                    regularization=0.01, 
                                    use_gpu=False, 
                                    iterations=15, 
                                    dtype=np.float32)

/Users/kenny_jung/Library/Python/3.9/lib/python/site-packages/implicit/cpu/als.py:95: RuntimeWarning: OpenBLAS is configured to use 10 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()


In [21]:
csr_data

<358869x291348 sparse matrix of type '<class 'numpy.int64'>'
	with 17535578 stored elements in Compressed Sparse Row format>

In [22]:
# # als 모델은 input으로 (item X user 꼴의 matrix를 받기 때문에 Transpose해줍니다.)
# csr_data_transpose = csr_data.T
# csr_data_transpose

In [23]:
# 모델 훈련
als_model.fit(csr_data)

  0%|          | 0/15 [00:00<?, ?it/s]

## Validation

In [30]:
print(type(als_model))

<class 'implicit.cpu.als.AlternatingLeastSquares'>


In [31]:
als_model.user_factors.shape

(291348, 100)

In [27]:
als_model.user_factors[kenny]

IndexError: index 358868 is out of bounds for axis 0 with size 291348

In [34]:
als_model.item_factors[kenny]

array([ 1.0569796e-03,  1.6271275e-03,  3.4018387e-03,  2.0396139e-03,
       -1.2863778e-04,  2.7161243e-03,  4.5132139e-04, -1.0172326e-04,
        2.0595891e-03,  1.9119498e-03,  7.9675420e-04,  1.5480899e-03,
        1.6993732e-03,  2.3941798e-03,  3.2134161e-03, -2.4834400e-04,
        1.8013602e-03,  3.4250824e-03,  1.1537423e-03,  2.8366863e-03,
       -9.0181049e-05,  9.2157710e-04,  1.5283284e-03,  9.0087886e-04,
        1.8918352e-03,  7.1378931e-04,  3.2286204e-03,  3.7796152e-04,
        1.0207933e-03,  2.0323840e-03,  5.3444365e-04,  1.9675549e-03,
        6.8314513e-04, -4.8791905e-04,  1.2086589e-03,  1.9403027e-03,
        1.1807012e-03,  6.8443286e-04,  3.4594438e-03, -5.5438857e-05,
        1.0600143e-04,  1.0380411e-03,  9.0910960e-04,  9.4300084e-04,
       -6.6371157e-04,  3.3147403e-03, -7.0617266e-04,  2.2661637e-03,
        2.5283054e-03,  5.9710018e-04, -8.8404056e-05,  1.0562588e-03,
        1.1701032e-03,  1.8733224e-03,  2.2891460e-03,  9.7224169e-04,
      

In [32]:
als_model.item_factors.shape

(358869, 100)

In [23]:
kenny, queen = user_to_idx['kenny'], artist_to_idx['queen']
kenny_vector, queen_vector = als_model.user_factors[kenny], als_model.item_factors[queen]

print('슝=3')

IndexError: index 358868 is out of bounds for axis 0 with size 291348

In [129]:
kenny_vector

array([-0.7289396 ,  0.36403078,  0.39346367, -0.63166   , -0.6612733 ,
        0.40955585, -0.43573117, -0.6121893 ,  1.2730095 ,  0.8027792 ,
       -0.09008019, -0.02366078,  0.783299  ,  0.19861455, -0.03020786,
        1.0890752 ,  0.42930025, -0.1030402 ,  1.2009258 ,  0.02411691,
       -0.92810434, -0.0534207 ,  1.2671402 ,  0.30801737, -0.03588085,
       -0.63945514, -0.6969064 , -1.5286965 ,  1.1099148 , -0.47346112,
       -1.1378608 , -0.64076096,  0.70440906,  0.53834206, -1.2508587 ,
        0.3093204 , -0.23437987, -0.7667511 , -1.4022284 ,  0.07485494,
        0.29928342,  0.16476111, -0.33903062,  0.13592157, -0.27857235,
        0.30460238, -0.46468198, -0.27743605, -0.00741507, -0.01639856,
        0.82985044,  0.17974612, -0.754822  ,  0.4336999 ,  0.42355075,
        0.603248  , -0.18473074, -0.685857  ,  0.8616526 , -0.5833419 ,
        0.15278015,  0.25558776,  0.88824797,  0.18344595, -0.04607799,
        0.0877228 , -0.18857002, -0.1413308 ,  0.21993278,  0.43

In [130]:
queen_vector

array([-0.00875096,  0.00202816,  0.01259404,  0.00979606,  0.0094179 ,
        0.01013605, -0.01646017,  0.01564625,  0.01500912,  0.01346073,
        0.00480652,  0.00116059,  0.01483558,  0.00791188,  0.01454636,
        0.01400146,  0.00981692, -0.01121775,  0.02330182,  0.01030055,
       -0.00097406,  0.00743687,  0.0073805 ,  0.01110268,  0.01443044,
        0.01553038,  0.00026605, -0.00983368,  0.01964808, -0.00680063,
        0.00247183,  0.00049375,  0.01844314,  0.0225145 , -0.00717863,
        0.01888355,  0.00975697, -0.00231706, -0.00790477,  0.00406005,
        0.00726318,  0.00820978, -0.00449356,  0.01403724, -0.00110394,
        0.00330409, -0.00133991,  0.01191232,  0.01997853,  0.0065667 ,
        0.01872448,  0.00224646, -0.00872771,  0.00727438,  0.02148732,
        0.01257226,  0.00334615, -0.00858051,  0.00923928, -0.00019875,
        0.00802893,  0.01536902,  0.00321087,  0.00322459,  0.01286251,
        0.01787338,  0.0223869 ,  0.01355398,  0.01815032,  0.02

In [131]:
# kenny과 queen를 내적하는 코드
np.dot(kenny_vector, queen_vector)

0.30574578

In [132]:
metallica = artist_to_idx['metallica']
metallica_vector = als_model.item_factors[metallica]
np.dot(kenny_vector, metallica_vector)

0.23535928

## Similar Artist

In [142]:
favorite_artist = 'coldplay'
artist_id = artist_to_idx[favorite_artist]
similar_artist = als_model.similar_items(artist_id, N=5)
similar_artist

(array([ 62, 277,  28,   5, 473], dtype=int32),
 array([0.9999999 , 0.9906012 , 0.98385835, 0.9837562 , 0.97577256],
       dtype=float32))

In [144]:
print(type(similar_artist))

<class 'tuple'>


In [145]:
# favorite_artist로부터 유사한 아티스트의 인덱스와 유사도 점수를 얻습니다.
similar_artist_indices, similarity_scores = similar_artist

# 유사한 아티스트의 인덱스를 사용하여 이름을 얻습니다.
similar_artist_names = [idx_to_artist[idx] for idx in similar_artist_indices]

print(similar_artist_names)

['coldplay', 'muse', 'the killers', 'red hot chili peppers', 'placebo']


In [149]:
similar_artist

(array([ 62, 277,  28,   5, 473], dtype=int32),
 array([0.9999999 , 0.9906012 , 0.98385835, 0.9837562 , 0.97577256],
       dtype=float32))

In [150]:
#artist_to_idx 를 뒤집어, index로부터 artist 이름을 얻는 dict를 생성합니다. 
idx_to_artist = {v:k for k,v in artist_to_idx.items()}
[idx_to_artist[idx] for idx in similar_artist[0]]

['coldplay', 'muse', 'the killers', 'red hot chili peppers', 'placebo']

In [152]:
def get_similar_artist(artist_name: str):
    artist_id = artist_to_idx[artist_name]
    similar_artist = als_model.similar_items(artist_id)
    similar_artist = [idx_to_artist[idx] for idx in similar_artist[0]]
    return similar_artist

print("슝=3")

슝=3


In [153]:
get_similar_artist('2pac')

['2pac',
 'dr. dre',
 'snoop dogg',
 'the game',
 'notorious b.i.g.',
 'nas',
 'ludacris',
 'jay-z',
 'dmx',
 '50 cent']

In [154]:
get_similar_artist('lady gaga')

['lady gaga',
 'britney spears',
 'rihanna',
 'katy perry',
 'beyoncé',
 'the pussycat dolls',
 'christina aguilera',
 'kelly clarkson',
 'justin timberlake',
 'leona lewis']

## Recommendation

In [157]:
user = user_to_idx['kenny']
print(user)

358868


In [155]:
user = user_to_idx['kenny']
# recommend에서는 user*item CSR Matrix를 받습니다.
artist_recommended = als_model.recommend(user, csr_data, N=20, filter_already_liked_items=True)
artist_recommended

ValueError: user_items must contain 1 row for every user in userids

In [ ]:
[idx_to_artist[i[0]] for i in artist_recommended]

In [ ]:
rihanna = artist_to_idx['rihanna']
explain = als_model.explain(user, csr_data, itemid=rihanna)

In [ ]:
[(idx_to_artist[i[0]], i[1]) for i in explain[1]]